services:
  devuntu:
    image: devuntu:latest
    container_name: devuntu
    ports:
      - 3000:3000
    volumes:
      - ./db:/app/db
      - ./upload:/app/upload
    restart: unless-stopped
    env_file: ./.env
