/** setup-env の表示メッセージ(英語)。キーは `lang-ja.mjs` と揃える */
/** @type {typeof import('./lang-ja.mjs').ja} */
export const en = {
  usage: `Usage: node scripts/setup-env/index.mjs [options]

  --dir <path>   Output directory (default: current directory)
  --dry-run      Show the generated content without writing files
  --force        Skip the overwrite confirmation
  --no-backup    Do not create .bak files of existing files
  --help         Show this usage
`,
  no_tty: 'Cannot read interactive input (no TTY is allocated).',
  no_tty_hint: 'Run it in one of the following ways.',
  aborted: 'Aborted (no files were written)',

  required: 'Required',
  treated_as: (value) => `Using ${value}`,
  answer_yes_no: 'Answer y or n',
  choice_number: 'Number',
  choose_number: (max) => `Choose a number from 1 to ${max}`,

  path_is_directory: (file) => `${file} is a directory.`,
  path_is_directory_hint: 'Docker created it in place of the config file. Remove it and run this again.',
  cannot_read: (file) => `Cannot read ${file}. Check the owner of the file`,
  s3_config_broken: (file) => `${file} is not valid JSON, so its content will be regenerated`,

  intro_title: 'Creating the config files for self-hosting Devuntu',
  intro_out_dir: (dir) => `Output: ${dir}`,
  intro_enter_default: 'Press Enter alone to use the default in []. Secret defaults are shown masked',
  intro_loaded_existing: 'Loaded the existing .env.docker and using its values as defaults',

  section_basic: 'Basic',
  section_database: 'Database',
  section_auth: 'Authentication',
  section_mail: 'Mail',
  section_storage: 'Object storage',
  section_integrations: 'External services',
  section_integrations_optional: 'External services (optional)',
  section_notify: 'Notifications',
  section_notify_optional: 'Notifications (optional)',
  section_maintenance: 'Maintenance',
  section_host_info: 'Host information',
  section_output: 'Generated content',
  section_extras: 'Others',

  q_default_locale: 'Default locale (DEFAULT_LOCALE)',
  q_default_locale_help: (choices) => `Choose from ${choices}`,
  q_default_timezone: 'Default time zone (DEFAULT_TIMEZONE)',

  q_use_bundled_db: 'Use the db service bundled in compose.yaml?',
  q_db_user: 'DB user (POSTGRES_USER)',
  q_db_password: 'DB password (POSTGRES_PASSWORD)',
  generated_default: 'The default is a generated value',
  q_db_name: 'DB name (POSTGRES_DB)',
  db_password_changed: [
    'postgres initializes its volume only on the first start. If you have already run docker compose up,',
    'changing the password here does not change the actual DB password and authentication will fail.',
    'To change it, recreate the volume (pgdata) or run ALTER USER on the DB.',
  ],
  q_database_url: 'Connection URL (DATABASE_URL)',
  q_database_url_help: 'Connects to an external PostgreSQL',
  bundled_db_removable: 'If you do not use the bundled db service, you may remove it from compose.yaml',

  q_better_auth_url: 'Public base URL (BETTER_AUTH_URL)',
  q_better_auth_url_help: 'Must exactly match the origin you serve from (otherwise sign-in POSTs are rejected)',
  q_regenerate_auth_secret: 'Regenerate BETTER_AUTH_SECRET? (all existing sessions will be invalidated)',
  auth_secret_generated: 'Generated BETTER_AUTH_SECRET',
  q_disable_password_auth: 'Disable password sign-in and allow email OTP only? (DISABLE_PASSWORD_AUTH)',
  q_two_fa_required: 'Require two-factor authentication? (TWO_FA_REQUIRED)',
  two_fa_note: 'Users must set up two-factor authentication after their first sign-in',
  q_oidc_dcr: 'Expose the MCP server? (OIDC_DCR_ENABLED)',

  otp_only_note: 'Password sign-in is disabled, so email OTP is the only way to sign in',
  q_mail_send: 'Delivery method (MAIL_SEND)',
  mail_debug_label: 'debug (do not send; print to the server log)',
  mail_none_label: 'none (do not send mail)',
  mail_none_warn: 'Without sending mail, nobody can sign in. For a trial, choose debug',
  q_mail_none_confirm: 'Leave mail unconfigured anyway?',
  q_mail_from: 'Sender address (MAIL_FROM)',
  q_sendgrid_api_key: 'SendGrid API key (SENDGRID_API_KEY)',
  sendgrid_key_prefix: 'SendGrid API keys usually start with SG.',
  q_sendmail_path: 'Path to sendmail (SENDMAIL_PATH)',
  sendmail_warn: [
    'The app container (based on node:24-slim) does not include sendmail.',
    'It only works if it can be resolved inside the container. Usually choose smtp / sendgrid',
  ],
  q_smtp_host: 'SMTP host (SMTP_HOST)',
  q_smtp_port: 'SMTP port (SMTP_PORT)',
  q_smtp_secure: 'Connect with SSL/TLS? (SMTP_SECURE)',
  q_smtp_ignore_tls: 'Connect without TLS? (SMTP_IGNORE_TLS)',
  q_smtp_auth: 'Configure SMTP authentication (user and password)?',
  q_smtp_user: 'SMTP user (SMTP_USER)',
  q_smtp_pass: 'SMTP password (SMTP_PASS)',
  mail_debug_note: 'OTPs are not sent but printed to the server log (docker compose logs devuntu)',

  q_use_bundled_s3: 'Use the SeaweedFS bundled in compose.yaml?',
  q_s3_endpoint: 'S3 API endpoint (S3_ENDPOINT)',
  q_s3_region: 'Region (S3_REGION)',
  q_s3_bucket: 'Bucket name (S3_BUCKET)',
  q_s3_bucket_help: 'Created automatically on the first upload if it does not exist',
  q_s3_access_key: 'Access key (S3_ACCESS_KEY_ID)',
  q_s3_secret_key: 'Secret key (S3_SECRET_ACCESS_KEY)',
  s3_config_same_values: 'seaweedfs-s3.json will be generated with the same values',

  q_google: 'Configure Google account integration?',
  q_client_id: (key) => `Client ID (${key})`,
  q_client_secret: (key) => `Client secret (${key})`,
  q_google_sign_in: 'Use it for Google sign-in (signing in with the account)?',
  q_google_allowed_domains: 'Domains allowed to sign in (GOOGLE_ALLOWED_DOMAINS)',
  q_google_allowed_domains_help: 'Comma-separated. If unset, sign-in from every domain is rejected',
  google_calendar_only: 'Only calendar integration is enabled (Google sign-in rejects every domain)',
  google_redirect_uris: 'Redirect URIs to register in Google Cloud:',
  q_slack: 'Configure Slack integration?',
  q_slack_bot_token: 'Bot token (SLACK_BOT_TOKEN)',
  slack_bot_token_prefix: 'Bot tokens usually start with xoxb-',
  q_slack_team_id: 'Workspace ID (SLACK_TEAM_ID)',
  slack_team_id_prefix: 'Workspace IDs usually start with T',
  q_slack_signing_secret: 'Signing secret (SLACK_SIGNING_SECRET)',
  q_gitlab: 'Configure GitLab integration (MR status and CI results)?',
  q_gitlab_urls: 'GitLab instance URLs (GITLAB_URLS)',
  q_gitlab_urls_help: 'Comma-separated for multiple (e.g. https://gitlab.com,https://git.example.com/gitlab)',
  gitlab_webhook_note:
    'The webhook URL and token are shown and set per project under "Git integration" in the board settings',
  q_web_push: 'Enable web push notifications?',
  q_regenerate_vapid: 'Regenerate the VAPID keys? (all existing subscriptions will be invalidated)',
  vapid_regenerated: 'Regenerated the VAPID keys',
  vapid_generated: 'Generated the VAPID keys',
  q_change_vapid_subject: 'Change the contact for push services from the default?',
  q_vapid_subject: 'Contact (VAPID_SUBJECT)',
  q_vapid_subject_help: 'Starts with mailto: or https:',
  web_push_needs_https: 'Browsers do not allow push subscriptions without HTTPS',

  key_not_writable: (key, reason) =>
    `${key}: ${reason}. This key cannot be kept (the original value remains in the backup file)`,
  carried_keys: (keys) => `Keeping the current values of these settings without asking: ${keys}`,
  unknown_keys: (keys) => `The existing .env.docker has keys this script does not manage: ${keys}`,
  q_keep_unknown_keys: 'Keep them as they are?',
  key_reason: (key, reason) => `${key}: ${reason}.`,
  no_backup_would_lose: 'Aborted because --no-backup would lose this value when overwriting.',
  no_backup_would_lose_hint: 'Run without --no-backup, or back up those keys manually first.',

  build_failed: (message) => `Could not build the config: ${message}`,
  env_docker_header: [
    'Environment variables for self-hosting Devuntu (regenerate with docker compose run --rm tools setup-env)',
    'See docs/admin/environment-variables.md for all variables',
  ],
  env_docker_extras: 'Others (settings not managed by this script)',
  env_db_header: [
    'Variables read by the db service (postgres) in compose.yaml',
    'When using an external PostgreSQL, this file and the db service are not needed',
  ],
  diff_title: 'Changes to .env.docker',
  diff_summary: (added, changed, removed) => `added ${added} / changed ${changed} / removed ${removed}`,
  diff_added: (keys) => `added: ${keys}`,
  diff_changed: (keys) => `changed: ${keys}`,
  diff_removed: (keys) => `removed: ${keys}`,
  dry_run_done: 'No files were written because of --dry-run',
  overwrite_files: (files) => `These files will be overwritten: ${files}`,
  q_write: 'Write the files?',

  cannot_write_dir: (dir) => `Cannot write to ${dir}. Check the owner of the directory, or run with sudo`,
  write_failed: (message) => `Failed to write: ${message}`,
  created: 'Created:',
  backed_up: (suffix) => `The previous content was saved to *.${suffix}.bak`,
  next_steps: 'Next steps:',
  next_open_start: (url) => `  Open ${url}/start and register the first administrator`,

  value_has_newline: 'values containing a newline cannot be written to an env file',
  value_has_single_quote: "values containing a single quote (') cannot be written to an env file",
  value_ends_with_backslash: 'values ending with a backslash cannot be written to an env file',

  vapid_generate_failed: 'Failed to generate the VAPID keys (the P-256 JWK is missing x / y / d)',
  invalid_url_example: 'Cannot be parsed as a URL (e.g. https://devuntu.example.com)',
  invalid_url: 'Cannot be parsed as a URL',
  invalid_url_value: (value) => `Cannot be parsed as a URL: ${value}`,
  http_or_https: 'Specify with http:// or https://',
  no_query_or_fragment: 'Query strings and fragments are not allowed',
  origin_only: (origin) => `Paths are not allowed (specify the origin only: ${origin})`,
  http_insecure: 'With http://, cookies are not marked Secure and browsers reject web push notifications',
  invalid_database_url:
    'Cannot be parsed as a connection URL (e.g. postgresql://user:pass@host:5432/dbname?schema=public)',
  postgresql_scheme: 'Specify with postgresql://',
  invalid_timezone: 'Cannot be parsed as a time zone name (e.g. Asia/Tokyo)',
  one_of: (choices) => `Specify one of ${choices}`,
  invalid_email: 'Specify an email address',
  invalid_port: 'Specify an integer from 1 to 65535',
  min_integer: (min) => `Specify an integer of ${min} or more`,
  allowed_domains_required: 'At least one is required (if unset, sign-in from every domain is rejected)',
  invalid_domain: (domain) => `Cannot be parsed as a domain name: ${domain}`,
  at_least_one: 'At least one is required',
  invalid_gitlab_url: (value) => `Specify a URL starting with http(s):// without credentials or a query: ${value}`,
  vapid_subject_scheme: 'Must start with mailto: or https:',
}
